export const locations = [
    { value: "1", label: "Aceh" },
    { value: "2", label: "Sumatera Utara" },
    { value: "3", label: "Sumatera Barat" },
    { value: "4", label: "Riau" },
    { value: "5", label: "Jambi" },
    { value: "6", label: "Sumatera Selatan" },
    { value: "7", label: "Bengkulu" },
    { value: "8", label: "Lampung" },
    { value: "9", label: "Kepulauan Bangka Belitung" },
    { value: "10", label: "Kepulauan Riau" },
    { value: "11", label: "DKI Jakarta" },
    { value: "12", label: "Jawa Barat" },
    { value: "13", label: "Jawa Tengah" },
    { value: "14", label: "DI Yogyakarta" },
    { value: "15", label: "Jawa Timur" },
    { value: "16", label: "Banten" },
    { value: "17", label: "Bali" },
    { value: "18", label: "Nusa Tenggara Barat" },
    { value: "19", label: "Nusa Tenggara Timur" },
    { value: "20", label: "Kalimantan Barat" },
    { value: "21", label: "Kalimantan Tengah" },
    { value: "22", label: "Kalimantan Selatan" },
    { value: "23", label: "Kalimantan Timur" },
    { value: "24", label: "Kalimantan Utara" },
    { value: "25", label: "Sulawesi Utara" },
    { value: "26", label: "Sulawesi Tengah" },
    { value: "27", label: "Sulawesi Selatan" },
    { value: "28", label: "Sulawesi Tenggara" },
    { value: "29", label: "Gorontalo" },
    { value: "30", label: "Sulawesi Barat" },
    { value: "31", label: "Maluku" },
    { value: "32", label: "Maluku Utara" },
    { value: "33", label: "Papua" },
    { value: "34", label: "Papua Barat" },
    { value: "35", label: "Papua Tengah" },
    { value: "36", label: "Papua Pegunungan" },
    { value: "37", label: "Papua Selatan" },
    { value: "38", label: "Papua Barat Daya" },
  ];
  
  export const categories = [
    { value: "1", label: "Comedy" },
    { value: "2", label: "Food" },
    { value: "3", label: "Education" },
    { value: "4", label: "Music" },
    { value: "5", label: "Film" },
  ];
  